apiVersion: apps/v1
kind: Deployment
metadata:
 name: bear deploy
spec:
 selector:
  matchLabels:
   app: bear
 replicas: 1
 template:
  metadata:
    labels:
      app: bear
  spec:
    containers:
    - name: bear containet
      image: supergiantkir/animals:bear
      ports:
      - containerPort: 80
      targetPort: 80
