apiVersion: apps/v1
kind: Deployment
metadata:
 name: bearDeploy
spec:
 selector:
  matchLabels:
   app: bear
 replicas: 1
 template:
  metadata:
    labels:
      app: bear
  spec:
    containers:
    - name: bearContainer
      image: supergiantkir/animals:bear
      ports:
      - containerPort: 80